services:
  # Aplikasi Web Anda
  my-web-app:
    image: ghcr.io/afaizr/uas-rpll:latest
    container_name: personal-web-app
    ports:
      - "3000:80" # Sesuaikan port aplikasi Anda (kiri: host, kanan: container)
    restart: always

  # Si Penjaga Otomatis (Watchtower)
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Kredensial untuk akses GHCR
      - REPO_USER=${GITHUB_USERNAME}
      - REPO_PASS=${GITHUB_PAT}
      # Pengaturan Watchtower
      - WATCHTOWER_POLL_INTERVAL=30 # Cek setiap 30 detik
      - WATCHTOWER_CLEANUP=true      # Hapus image lama agar SSD Mac tidak penuh
      - WATCHTOWER_LABEL_ENABLE=false # Memantau semua container yang running